-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 19:46:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smartcupon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartcupon` ;

-- -----------------------------------------------------
-- Schema smartcupon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartcupon` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `smartcupon` ;

-- -----------------------------------------------------
-- Table `smartcupon`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartcupon`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellidoMaterno` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(100) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `correoElectronico` ON `smartcupon`.`cliente` (`correoElectronico` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`tipo_promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`tipo_promocion` (
  `idTipoPromocion` INT NOT NULL AUTO_INCREMENT,
  `nombreTipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTipoPromocion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartcupon`.`estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`estatus` (
  `idEstatus` INT NOT NULL AUTO_INCREMENT,
  `nombreEstatus` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEstatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartcupon`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`empresa` (
  `RFC` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `nombreComercial` VARCHAR(255) NULL DEFAULT NULL,
  `representanteLegal` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `paginaWeb` VARCHAR(255) NULL DEFAULT NULL,
  `estatusID` INT NULL DEFAULT '1',
  `logo` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`RFC`),
  CONSTRAINT `empresa_ibfk_1`
    FOREIGN KEY (`estatusID`)
    REFERENCES `smartcupon`.`estatus` (`idEstatus`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `RFC_UNIQUE` ON `smartcupon`.`empresa` (`RFC` ASC) VISIBLE;

CREATE INDEX `estatusID` ON `smartcupon`.`empresa` (`estatusID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`promocion` (
  `idPromocion` INT NOT NULL AUTO_INCREMENT,
  `nombrePromocion` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fechaInicio` DATE NULL DEFAULT NULL,
  `fechaTermino` DATE NULL DEFAULT NULL,
  `restricciones` TEXT NULL DEFAULT NULL,
  `idTipoPromocion` INT NULL DEFAULT NULL,
  `porcentajeDescuento` DECIMAL(5,2) NULL DEFAULT NULL,
  `codigoPromocion` VARCHAR(8) NULL DEFAULT NULL,
  `idEstatus` INT NULL DEFAULT '1',
  `empresaRFC` VARCHAR(20) NOT NULL,
  `idCategoria` INT NULL DEFAULT NULL,
  `imagen` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idPromocion`),
  CONSTRAINT `categoriaID`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `smartcupon`.`categoria` (`idCategoria`),
  CONSTRAINT `promocion_ibfk_1`
    FOREIGN KEY (`idTipoPromocion`)
    REFERENCES `smartcupon`.`tipo_promocion` (`idTipoPromocion`),
  CONSTRAINT `promocion_ibfk_2`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `smartcupon`.`estatus` (`idEstatus`),
  CONSTRAINT `promocion_ibfk_3`
    FOREIGN KEY (`empresaRFC`)
    REFERENCES `smartcupon`.`empresa` (`RFC`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `codigoPromocion` ON `smartcupon`.`promocion` (`codigoPromocion` ASC) VISIBLE;

CREATE INDEX `empresaRFC` ON `smartcupon`.`promocion` (`empresaRFC` ASC) VISIBLE;

CREATE INDEX `promocion_ibfk_1` ON `smartcupon`.`promocion` (`idTipoPromocion` ASC) VISIBLE;

CREATE INDEX `promocion_ibfk_2` ON `smartcupon`.`promocion` (`idEstatus` ASC) VISIBLE;

CREATE INDEX `categoriaID` ON `smartcupon`.`promocion` (`idCategoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`cupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`cupon` (
  `idCupon` INT NOT NULL AUTO_INCREMENT,
  `codigoCupon` VARCHAR(8) NOT NULL,
  `idPromocion` INT NOT NULL,
  `fechaGeneracion` DATE NULL DEFAULT NULL,
  `idEstatus` INT NULL DEFAULT NULL,
  `usosDisponibles` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idCupon`),
  CONSTRAINT `cupon_ibfk_1`
    FOREIGN KEY (`idPromocion`)
    REFERENCES `smartcupon`.`promocion` (`idPromocion`),
  CONSTRAINT `cupon_ibfk_2`
    FOREIGN KEY (`idEstatus`)
    REFERENCES `smartcupon`.`estatus` (`idEstatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `codigoCupon` ON `smartcupon`.`cupon` (`codigoCupon` ASC) VISIBLE;

CREATE INDEX `cupon_ibfk_2` ON `smartcupon`.`cupon` (`idEstatus` ASC) VISIBLE;

CREATE INDEX `cupon_ibfk_1` ON `smartcupon`.`cupon` (`idPromocion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `nombreEstado_UNIQUE` ON `smartcupon`.`estado` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  CONSTRAINT `idEstado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `smartcupon`.`estado` (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idEstado_idx` ON `smartcupon`.`municipio` (`idEstado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `latitud` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitud` DECIMAL(11,8) NULL DEFAULT NULL,
  `nombreEncargado` VARCHAR(255) NULL DEFAULT NULL,
  `empresaRFC` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idSucursal`),
  CONSTRAINT `sucursal_ibfk_1`
    FOREIGN KEY (`empresaRFC`)
    REFERENCES `smartcupon`.`empresa` (`RFC`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `empresaRFC` ON `smartcupon`.`sucursal` (`empresaRFC` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(255) NOT NULL,
  `numero` INT NOT NULL,
  `codigoPostal` VARCHAR(10) NULL DEFAULT NULL,
  `colonia` VARCHAR(100) NULL DEFAULT NULL,
  `idMunicipio` INT NULL DEFAULT NULL,
  `idCliente` INT NULL DEFAULT NULL,
  `empresaRFC` VARCHAR(45) NULL DEFAULT NULL,
  `idSucursal` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idDireccion`),
  CONSTRAINT `empresaRFC`
    FOREIGN KEY (`empresaRFC`)
    REFERENCES `smartcupon`.`empresa` (`RFC`),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `smartcupon`.`cliente` (`idCliente`),
  CONSTRAINT `idMunicipio`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `smartcupon`.`municipio` (`idMunicipio`),
  CONSTRAINT `idSucursal`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `smartcupon`.`sucursal` (`idSucursal`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `empresaRFC_idx` ON `smartcupon`.`direccion` (`empresaRFC` ASC) VISIBLE;

CREATE INDEX `idCliente_idx` ON `smartcupon`.`direccion` (`idCliente` ASC) VISIBLE;

CREATE INDEX `idSucursal_idx` ON `smartcupon`.`direccion` (`idSucursal` ASC) VISIBLE;

CREATE INDEX `idMunicipio_idx` ON `smartcupon`.`direccion` (`idMunicipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartcupon`.`sucursal_promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`sucursal_promocion` (
  `idSucursalPromocion` INT NOT NULL AUTO_INCREMENT,
  `sucursalID` INT NULL DEFAULT NULL,
  `promocionID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSucursalPromocion`),
  CONSTRAINT `sucursal_promocion_ibfk_1`
    FOREIGN KEY (`sucursalID`)
    REFERENCES `smartcupon`.`sucursal` (`idSucursal`),
  CONSTRAINT `sucursal_promocion_ibfk_2`
    FOREIGN KEY (`promocionID`)
    REFERENCES `smartcupon`.`promocion` (`idPromocion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `sucursalID` ON `smartcupon`.`sucursal_promocion` (`sucursalID` ASC) VISIBLE;

CREATE INDEX `promocionID` ON `smartcupon`.`sucursal_promocion` (`promocionID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `smartcupon`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartcupon`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellidoMaterno` VARCHAR(100) NULL DEFAULT NULL,
  `CURP` VARCHAR(18) NOT NULL,
  `correoElectronico` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rolID` INT NOT NULL,
  `empresaRFC` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`rolID`)
    REFERENCES `smartcupon`.`rol` (`idRol`),
  CONSTRAINT `usuario_ibfk_2`
    FOREIGN KEY (`empresaRFC`)
    REFERENCES `smartcupon`.`empresa` (`RFC`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `CURP` ON `smartcupon`.`usuario` (`CURP` ASC) VISIBLE;

CREATE UNIQUE INDEX `correoElectronico` ON `smartcupon`.`usuario` (`correoElectronico` ASC) VISIBLE;

CREATE UNIQUE INDEX `username` ON `smartcupon`.`usuario` (`username` ASC) VISIBLE;

CREATE INDEX `usuario_ibfk_1` ON `smartcupon`.`usuario` (`rolID` ASC) VISIBLE;

CREATE INDEX `usuario_ibfk_2` ON `smartcupon`.`usuario` (`empresaRFC` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
